### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by wang357911** [laiguokun/bert-cloth#2]
I can not receive the e-mail after send the message by website

**Comment by laiguokun** [comment]
Please try the link http://www.cs.cmu.edu/~glai1/data/cloth/. Notice that our website doesn't support https. If it still doesn't work, please email me.

**Comment by wang357911** [comment]
sorry to border you, I try the link with http, but the send button is loading for a long time and I can not download the dataset. the button looks like the picture shows. 





------------------ 原始邮件 ------------------
发件人: "GUOKUN LAI"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 中午11:52
收件人: "laiguokun/bert-cloth"<bert-cloth@noreply.github.com>;
抄送: "994980644"<994980644@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [laiguokun/bert-cloth] question about dataset (#2)




Please try the link http://www.cs.cmu.edu/~glai1/data/cloth/. Notice that our website doesn't support https.

**Comment by laiguokun** [comment]
Please send me an email with the email box that you want to receive the dataset.

**Comment by vqiangv** [comment]
> Please send me an email with the email box that you want to receive the dataset.

您好，很抱歉打扰您，CLOTH的数据集可以发给我一份嘛，我的邮箱：v_qiang@qq.com，万分感谢！！！
